site_name: ClickUz




nav:
  - Kirish: index.md
  - Ishni boshlash: getting_started.md
  - Url yaratish: generate_url.md
  - Buyurtmani tekshirish: check_order.md





google_analytics:
  - UA-133183413-1
  - auto




markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - js/termynal.js
  - js/custom.js
  - js/chat.js


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/begyy/ClickUz'


